name: Linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }} ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ruff and Prettier
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          npm install -g prettier

      - name: Check Prettier formatting
        run: prettier --check .

      - name: Check Python script formatting
        run: ruff format --check bin/

      - name: Lint Python scripts
        run: ruff check --extend-select I bin/

  pipeline_linting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pipeline tools
        run: |
          python -m pip install --upgrade pip
          pip install nf-core

      - name: Lint local Nextflow scripts
        run: |
          find main.nf workflows/ subworkflows/local modules/local \
          -exec nextflow lint -format -sort-declarations -harshil-alignment {} + \
          | (! grep 'formatted') \
          || (echo 'Some Nextflow scripts were not formatted properly!' && exit 1)

      - name: Lint modules
        run: nf-core --hide-progress modules lint --all

      - name: Lint subworkflows
        run: nf-core --hide-progress subworkflows lint --all